---
- name: Install docker
  ansible.builtin.apt:
    name: docker.io
    update_cache: yes
    state: latest
- name: Start docker
  ansible.builtin.systemd:
    state: started
    name: docker
- name: Swap off
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^(?!#)(.*swap.*)'
    replace: '#\1'
  register: results
- name: Reboot for swap off
  ansible.builtin.reboot:
    reboot_timeout: 3600
  when: results.changed
- name: Set memory to results
  ansible.builtin.command:
    cmd: free
  changed_when: results['rc'] != 0
  register: results
- name: Check swap is zero
  ansible.builtin.fail:
  loop: '{{ (results.stdout_lines[2] | regex_replace("\s+", " ")).split(" ") }}'
  when: item not in ['Swap:', '0']
- name: Modprove br_netfilter
  ansible.builtin.command:
    cmd: modprobe br_netfilter
  changed_when: results['rc'] != 0
- name: Set bridge-nf-call-iptables to results
  ansible.builtin.command:
    cmd: cat /proc/sys/net/bridge/bridge-nf-call-iptables
  register: results
  changed_when: results['rc'] != 0
- name: Check bridge-nf-call-iptables == 1
  block:
    - name: Copy k8s.conf
      ansible.builtin.copy:
        src: k8s.conf
        dest: /etc/sysctl.d/k8s.conf
    - name: Sysctl reload
      ansible.builtin.command:
        cmd: sysctl --system
    - name: Recheck bridge-nf-call-iptables
      ansible.builtin.command:
        cmd: cat /proc/sys/net/bridge/bridge-nf-call-iptables
      register: results
      failed_when: results.stdout[0] == "0"
  when: results.stdout[0] == "0"
- name: Allow port in worker
  block:
    - name: Install firewalld
      ansible.builtin.apt:
        name: firewalld
    - name: Allow kubectl port
      ansible.posix.firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
      with_items:
        - 10250/tcp
        - 10250/udp
    - name: Alow NodePort
      ansible.posix.firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
      with_items:
        - 30000-32767/tcp
        - 30000-32767/udp     
    - name: reload service firewalld
      ansible.builtin.systemd:
        name: firewalld
        state: reloaded
      changed_when: false
  when: "'worker' in group_names"
- name: Allow port in master 
  block:
    - name: Install firewalld
      ansible.builtin.apt:
        name: firewalld
    - name: Allow port
      ansible.posix.firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
      with_items:
        - 6443/tcp
        - 6443/udp
        - 2379-2380/tcp
        - 2379-2380/udp
        - 10250/tcp
        - 10250/udp
        - 10251/tcp
        - 10251/udp
        - 10252/tcp
        - 10252/udp
    - name: reload service firewalld
      ansible.builtin.systemd:
        name: firewalld
        state: reloaded
      changed_when: false
  when: "'master' in group_names"